project:
  type: website
  output-dir: docs

from: markdown+emoji

website:
  title: "Wei Jing Ang"
  page-navigation: true
  
  sidebar:
    # - id: projects
    #   title: "Projects"
    #   style: "floating"
    #   align: left
    #   contents:
    #     - text: "Projects"
    #       href: projects/index.qmd
    #     - text: "Amazon"
    #       href: projects/Amazon/index.qmd
    #     - text: "Lakes"
    #       href: projects/Lakes/index.qmd
    #     - text: "Mekong"
    #       href: projects/Mekong/index.qmd

    - id: collection
      contents:
        - text: "Collection"
          href: collection/index.qmd
        - text: "Maps" 
          href: collection/maps.qmd
        - text: "Photographs"
          href: collection/photographs.qmd
        - text: "Diagrams"
          href: collection/diagrams.qmd

  navbar:
    title: false
    background: light
    foreground: dark
    left:
      - text: '<img src="/images/logo.png" alt="Logo" style="height:60px;">'
        href: index.html
    right:
      - text: "Home"
        href: index.qmd
      - text: "Projects"
        href: projects/index.qmd
      - text: "Collection"
        href: collection/index.qmd
        
  page-footer:
    right: "This page is built with {{< fa heart >}} and [Quarto](https://quarto.org/)."
    left: "2024, WJA"

format: 
  html:
    theme: 
    - sandstone
    - custom.scss
    
execute:
  freeze: auto
    
# Design tips:
# 1. maggieappleton.com
