project:
  type: website
  output-dir: docs

from: markdown+emoji

website:
  title: "Wei Jing Ang"
  page-navigation: true
  
  sidebar:
    - id: projects
      title: "Projects"
      style: "floating"
      align: left
      contents:
        - text: "Projects"
          href: projects/index.qmd
        - text: "1. Welcome to Quarto"
          href: projects/1-welcome-to-quarto/index.qmd
        - text: "2. Polishing Documents"
          href: projects/2-polishing-documents/index.qmd
        - text: "3. Computation"
          href: projects/3-computation/index.qmd
        - text: "4. Projects and Publishing"
          href: projects/4-projects-and-publishing/index.qmd

    - id: collection
      contents:
        - collection.qmd
  
  navbar:
    background: light
    foreground: dark
    right:
      - text: "Home"
        href: index.qmd
      - text: "Projects"
        href: projects/index.qmd
      - text: "Collection"
        href: collection.qmd
        
  page-footer:
    right: "This page is built with {{< fa heart >}} and [Quarto](https://quarto.org/)."
    left: "2024, Wei Jing Ang"

format: 
  html:
    theme: 
    - sandstone
    - custom.scss
    
execute:
  freeze: auto
    
# Design tips:
# 1. maggieappleton.com
